mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" << EOF
    CREATE DATABASE CitizenProposalApp;
    GRANT SELECT, INSERT, UPDATE, DELETE ON CitizenProposalApp.* TO "${MYSQL_USER}";

    CREATE USER Migrator IDENTIFIED BY RANDOM PASSWORD;
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, REFERENCES, INDEX ON CitizenProposalApp.* TO Migrator;
EOF
