services:
  backend:
    build: backend
    networks:
      - citizen-proposal-app
    ports:
      - 80:8080
      - 443:8081
  db:
    image: mysql:8.0.36 # The current latest supported version by Pomelo.EntityFrameworkCore.MySql
    networks:
      - citizen-proposal-app
    ports:
      - 37591:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=$MYSQL_RANDOM_ROOT_PASSWORD

networks:
  citizen-proposal-app:
    name: citizen-proposal-app # Prevents project prefix; otherwise it becomes <repo_directory_name>_citizen-proposal-app
    attachable: true

volumes:
  mysql-data:
    name: mysql-data # Prevents project prefix
