/* tslint:disable */
/* eslint-disable */
/**
 * Citizen Proposal App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The DTO used as the response body when the AI service checks if a piece of text or image is appropriate.
 * @export
 * @interface AiSafetyQueryResponseDto
 */
export interface AiSafetyQueryResponseDto {
    /**
     * true if the piece of text or image is appropriate.
     * @type {boolean}
     * @memberof AiSafetyQueryResponseDto
     */
    isSafe: boolean;
}

/**
 * Check if a given object implements the AiSafetyQueryResponseDto interface.
 */
export function instanceOfAiSafetyQueryResponseDto(value: object): value is AiSafetyQueryResponseDto {
    if (!('isSafe' in value) || value['isSafe'] === undefined) return false;
    return true;
}

export function AiSafetyQueryResponseDtoFromJSON(json: any): AiSafetyQueryResponseDto {
    return AiSafetyQueryResponseDtoFromJSONTyped(json, false);
}

export function AiSafetyQueryResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiSafetyQueryResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'isSafe': json['isSafe'],
    };
}

export function AiSafetyQueryResponseDtoToJSON(json: any): AiSafetyQueryResponseDto {
    return AiSafetyQueryResponseDtoToJSONTyped(json, false);
}

export function AiSafetyQueryResponseDtoToJSONTyped(value?: AiSafetyQueryResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isSafe': value['isSafe'],
    };
}

