/* tslint:disable */
/* eslint-disable */
/**
 * Citizen Proposal App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VoteKind } from './VoteKind';
import {
    VoteKindFromJSON,
    VoteKindFromJSONTyped,
    VoteKindToJSON,
    VoteKindToJSONTyped,
} from './VoteKind';

/**
 * Used as the response body when querying what kind of vote a user has cast on a post.
 * @export
 * @interface CurrentUserVoteQueryResponseDto
 */
export interface CurrentUserVoteQueryResponseDto {
    /**
     * 
     * @type {VoteKind}
     * @memberof CurrentUserVoteQueryResponseDto
     */
    voteKind: VoteKind;
}



/**
 * Check if a given object implements the CurrentUserVoteQueryResponseDto interface.
 */
export function instanceOfCurrentUserVoteQueryResponseDto(value: object): value is CurrentUserVoteQueryResponseDto {
    if (!('voteKind' in value) || value['voteKind'] === undefined) return false;
    return true;
}

export function CurrentUserVoteQueryResponseDtoFromJSON(json: any): CurrentUserVoteQueryResponseDto {
    return CurrentUserVoteQueryResponseDtoFromJSONTyped(json, false);
}

export function CurrentUserVoteQueryResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUserVoteQueryResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'voteKind': VoteKindFromJSON(json['voteKind']),
    };
}

export function CurrentUserVoteQueryResponseDtoToJSON(json: any): CurrentUserVoteQueryResponseDto {
    return CurrentUserVoteQueryResponseDtoToJSONTyped(json, false);
}

export function CurrentUserVoteQueryResponseDtoToJSONTyped(value?: CurrentUserVoteQueryResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'voteKind': VoteKindToJSON(value['voteKind']),
    };
}

