/* tslint:disable */
/* eslint-disable */
/**
 * Citizen Proposal App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What key to sort posts with when querying multiple posts.
 * @export
 */
export const PostSortKey = {
    ByDate: 'byDate',
    ById: 'byId'
} as const;
export type PostSortKey = typeof PostSortKey[keyof typeof PostSortKey];


export function instanceOfPostSortKey(value: any): boolean {
    for (const key in PostSortKey) {
        if (Object.prototype.hasOwnProperty.call(PostSortKey, key)) {
            if (PostSortKey[key as keyof typeof PostSortKey] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PostSortKeyFromJSON(json: any): PostSortKey {
    return PostSortKeyFromJSONTyped(json, false);
}

export function PostSortKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSortKey {
    return json as PostSortKey;
}

export function PostSortKeyToJSON(value?: PostSortKey | null): any {
    return value as any;
}

export function PostSortKeyToJSONTyped(value: any, ignoreDiscriminator: boolean): PostSortKey {
    return value as PostSortKey;
}

