/* tslint:disable */
/* eslint-disable */
/**
 * Citizen Proposal App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The DTO used as the response body of user queries.
 * @export
 * @interface UserQueryResponseDto
 */
export interface UserQueryResponseDto {
    /**
     * The primary key.
     * @type {number}
     * @memberof UserQueryResponseDto
     */
    id: number;
    /**
     * The username. The max length is 32.
     * @type {string}
     * @memberof UserQueryResponseDto
     */
    username: string;
}

/**
 * Check if a given object implements the UserQueryResponseDto interface.
 */
export function instanceOfUserQueryResponseDto(value: object): value is UserQueryResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UserQueryResponseDtoFromJSON(json: any): UserQueryResponseDto {
    return UserQueryResponseDtoFromJSONTyped(json, false);
}

export function UserQueryResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserQueryResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
    };
}

export function UserQueryResponseDtoToJSON(json: any): UserQueryResponseDto {
    return UserQueryResponseDtoToJSONTyped(json, false);
}

export function UserQueryResponseDtoToJSONTyped(value?: UserQueryResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
    };
}

